KEYCLOAK_DB_NAME: "keycloak"
KEYCLOAK_DB_USER: "keycloak"
KEYCLOAK_DB_PORT: 5432
KEYCLOAK_DB_VENDOR: "postgres"

KEYCLOAK_DOCKER_IMAGE: "jboss/keycloak"
KEYCLOAK_DOCKER_IMAGE_TAG: "latest"
KEYCLOAK_RESTART_POLICY_CONDITION: "any"

KEYCLOAK_DIST_DIR: "/opt/keycloak"
